=== tmullin/jshmanager-legacy-sf-www/htdocs/version.dtd
<!ELEMENT versionInfo (latest, versions)>
<!ELEMENT latest EMPTY>
<!ATTLIST latest
	version CDATA #REQUIRED
>

<!ELEMENT versions (version*)>
<!ELEMENT version EMPTY>
<!ATTLIST version
	version CDATA #REQUIRED
	oldVersion CDATA #REQUIRED
	url CDATA #REQUIRED
	directUrl CDATA #REQUIRED
>

=== tmullin/jshmanager-legacy-sf-www/htdocs/version.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE versionInfo SYSTEM "http://jshm-s3.tmullin.net/version.dtd">

<versionInfo>
	<latest version="0.3.6"/>

	<versions>
		<version
			version="0.3.6"
			oldVersion="0.3.5"
			url="http://github.com/tmullin/jshmanager-jshm/releases/tag/JSHManager-0.3.6"
			directUrl=""/>
		<version
			version="0.3.5"
			oldVersion="0.3.4"
			url="http://sourceforge.net/projects/jshm/files/jshm/0.3.5"
			directUrl="http://downloads.sourceforge.net/jshm/JSHManager-patch-0.3.4-to-0.3.5.442.jar"/>
		<version
			version="0.3.4"
			oldVersion="0.3.3"
			url="http://sourceforge.net/projects/jshm/files/jshm/0.3.4"
			directUrl="http://downloads.sourceforge.net/jshm/JSHManager-patch-0.3.3-to-0.3.4.436.jar"/>
		<version
			version="0.3.3"
			oldVersion="0.3.2"
			url="http://sourceforge.net/projects/jshm/files/jshm/0.3.3"
			directUrl="http://downloads.sourceforge.net/jshm/JSHManager-patch-0.3.2-to-0.3.3.425.jar"/>
		<version
			version="0.3.2"
			oldVersion="0.3.1"
			url="http://sourceforge.net/projects/jshm/files/jshm/0.3.2"
			directUrl="http://downloads.sourceforge.net/jshm/JSHManager-patch-0.3.1-to-0.3.2.412.jar"/>
		<version
			version="0.3.1"
			oldVersion="0.3.0"
			url="http://sourceforge.net/projects/jshm/files/jshm/0.3.1"
			directUrl="http://downloads.sourceforge.net/jshm/JSHManager-patch-0.3.0-to-0.3.1.388.jar"/>
		<version
			version="0.3.0"
			oldVersion="0.2.8"
			url="http://sourceforge.net/projects/jshm/files/jshm/0.3.0"
			directUrl=""/>
	</versions>
</versionInfo>
